image: docker:latest

stages:
  - build

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  
build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker image build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker image push $CONTAINER_RELEASE_IMAGE